web:
  build: .
  command: 'bash -c ''java $JAVA_OPTS -jar target/dependency/webapp-runner.jar --port $PORT target/*.war'''
  working_dir: \app\user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
shell:
  build: .
  command: bash
  working_dir: \app\user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:\app\user'
